### GET request to example server
PUT http://localhost:8083/connectors/file-stream-sink/config
Content-Type: application/json

{
  "name": "file-stream-sink",
  "connector.class": "org.apache.kafka.connect.file.FileStreamSinkConnector",
  "tasks.max": "1",
  "topics": "mytopic",
  "file": "mytopic.out",
  "value.converter": "org.apache.kafka.connect.storage.StringConverter"
}

###