services:

  nifi:
    image: apache/nifi:1.21.0
    container_name: nifi
    user: "root"
    ports:
      - "8081:8081"
    environment:
      NIFI_WEB_HTTP_PORT: 8081
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current/data
      - ./nifi:/opt/nifi/sec
    networks:
      - nifi_net

volumes:
  nifi_data:

networks:
  nifi_net:
    external: true