version: "3.5"

x-kafka-common: &kafka-common
  image: bitnami/kafka:3.7
  restart: always
  networks:
    - proxynet_sprint_6

x-kafka-common-env: &kafka-common-env
  KAFKA_ENABLE_KRAFT: yes
  ALLOW_PLAINTEXT_LISTENER: yes
  KAFKA_KRAFT_CLUSTER_ID: practicum
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,BROKER:PLAINTEXT"
  KAFKA_CFG_PROCESS_ROLES: broker,controller
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false

services:

  kafka-0:
    <<: *kafka-common
    container_name: kafka-0
    ports:
      - "127.0.0.1:9094:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_LISTENERS: BROKER://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://kafka-0:9092,EXTERNAL://127.0.0.1:9094
    volumes:
      - kafka_0_data_sprint_6:/bitnami/kafka

  kafka-1:
    <<: *kafka-common
    container_name: kafka-1
    ports:
      - "127.0.0.1:9095:9095"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: BROKER://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://kafka-1:9092,EXTERNAL://127.0.0.1:9095
    volumes:
      - kafka_1_data_sprint_6:/bitnami/kafka

  kafka-2:
    <<: *kafka-common
    container_name: kafka-2
    ports:
      - "127.0.0.1:9096:9096"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: BROKER://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://kafka-2:9092,EXTERNAL://127.0.0.1:9096
    volumes:
      - kafka_2_data_sprint_6:/bitnami/kafka

  schema-registry:
    image: bitnami/schema-registry:7.6
    ports:
      - '127.0.0.1:8081:8081'
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka-0:9092,PLAINTEXT://kafka-1:9092,PLAINTEXT://kafka-2:9092
    networks:
      - proxynet_sprint_6

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    restart: always
    ports:
      - "127.0.0.1:8086:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092
      KAFKA_CLUSTERS_0_NAME: kraft
    networks:
      - proxynet_sprint_6

networks:
  proxynet_sprint_6:
    name: proxynet_sprint_6
    external: true

volumes:
  kafka_0_data_sprint_6:
  kafka_1_data_sprint_6:
  kafka_2_data_sprint_6: