services:

  hadoop-namenode:
    image: apache/hadoop:3.4.1
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    user: "root"
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2g"
    shm_size: 10G
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site-namenode.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "/scripts/namenode_entrypoint.sh"]
    command: ["hdfs", "namenode"]

  hadoop-datanode-1:
    image: apache/hadoop:3.4.1
    container_name: hadoop-datanode-1
    hostname: hadoop-datanode-1
    user: "root"
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2g"
    shm_size: 10G
    depends_on:
      - hadoop-namenode
    ports:
      - "9864:9864"
      - "9970:9970"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site-datanode-1.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "/scripts/datanode_entrypoint.sh"]
    command: ["hdfs", "datanode"]

  #spark-master:
  #  image: bitnami/spark:3.5.4
  #  container_name: spark-master
  #  ports:
  #    - "8080:8080"
  #    - "7077:7077"
  #  environment:
  #    SPARK_MODE: master
  #    SPARK_MASTER_HOST: spark-master
  #
  #spark-worker-1:
  #  image: bitnami/spark:3.5.4
  #  container_name: spark-worker-1
  #  depends_on:
  #    - spark-master
  #  environment:
  #    SPARK_MODE: worker
  #    SPARK_MASTER_URL: spark://spark-master:7077
  #
  #spark-worker-2:
  #  image: bitnami/spark:3.5.4
  #  container_name: spark-worker-2
  #  depends_on:
  #    - spark-master
  #  environment:
  #    SPARK_MODE: worker
  #    SPARK_MASTER_URL: spark://spark-master:7077

networks:
  proxynet:

volumes:
  kafka_0_data:
  kafka_1_data:
