services:

  sprint_2_app:
    image: sprint_2_app:latest
    networks:
      - sprint_2_app_net
      - sprint_2_kafka_net
    environment:
      - NUMBER_OF_MESSAGES=100

networks:
  sprint_2_app_net:
    external: true
  sprint_2_kafka_net:
    external: true