number-of-messages: 1
leader:
  host: rc1a-s89utbdt01tfp6hh.mdb.yandexcloud.net:9091
schema-registry:
  url: https://rc1a-s89utbdt01tfp6hh.mdb.yandexcloud.net:443
  user: sr-user
  password: sr-user-password
jaas-template: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"%s\" password=\"%s\";"
task-1:
  topic: cluster-topic
  producer:
    user: kafka-producer
    password: kafka-producer-password
  consumer:
    user: kafka-consumer
    password: kafka-consumer-password
  cacerts:
    location: C:\\jdk\\java17\\lib\\security\\cacerts
    password: changeit

