cluster:
  leader-host: localhost:9094
  #leader-host: rc1a-gtaf31j62r39nl99.mdb.yandexcloud.net:9091
  security:
    enabled: false
    jaas-template: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"%s\" password=\"%s\";"
    cacerts:
      location: C:\\jdk\\java17\\lib\\security\\cacerts
      password: "changeit"

schema-registry:
  url: https://rc1a-s89utbdt01tfp6hh.mdb.yandexcloud.net:443
  user: "sr-user"
  password: "sr-user-password"

shop:
  delay: 500
  topic: "data-products-topic-raw"
  user:
    username: "shop-user"
    password: "shop-user-password"

client:
  topic: "data-client-requests-topic"
  user:
    username: "client-user"
    password: "client-user-password"

hdfs:
  url: "hdfs://localhost:9000"
  file-path: "/data/{%s}/{%s}"
  topics: "data-products-topic-filtered,data-client-requests-topic"
  user:
    username: "hdfs-user"
    password: "hdfs-user-password"

product-filter:
  app-id: "product-filter-app"
  forbidden-product-ids: "504d0f30-0ed0-4a14-9857-e48e70226820,19c2e1b4-e348-4bf0-bc15-700820a34d16,c0dffd6e-9332-4a93-97ef-e225f243ff83,c772da32-e8c9-4cd1-a236-4dfad02c844f"
  topics:
    forbidden-list: "forbidden-products-topic"
    source: "data-products-topic-raw"
    sink: "data-products-topic"
  user:
    username: "filter-user"
    password: "filter-user-password"
