FQDN-cluster: "rc1a-cl25ldolj3okh20q.mdb.yandexcloud.net"
FQDN-replica: "rc1a-16eqvk8dq4fb9i47.mdb.yandexcloud.net"
cluster:
  leader-host: "${FQDN-cluster}:9091"
  security:
    enabled: true
    jaas-template: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"%s\" password=\"%s\";"
    cacerts:
      location: ${user.dir}\project\src\main\resources\cacerts
      password: "changeit"

replica:
  leader-host: ${FQDN-replica}:9091

shop:
  enabled: true
  delay: 50
  topic: "data-products-topic-raw"
  user:
    username: "shop-user"
    password: "shop-user-password"

client:
  enabled: true
  producer-topic: "data-client-requests-topic"
  consumer-topic: "data-client-products-topic"
  consumer-recommendation-topic: "data-client-products-recommendation-topic"
  consumer-test-topic: "data-products-topic"
  poll-count: 5
  poll-duration: 2
  user:
    username: "client-user"
    password: "client-user-password"

hdfs:
  group-id: hdfs-replica-2
  disabled: false
  url: "hdfs://localhost:9000"
  file-path: "hdfs://localhost:9000/data/entry_"
  topics: "data-client-requests-topic"
  user:
    username: "hdfs-user"
    password: "hdfs-user-password"

product-filter:
  enabled: true
  app-id: "product-filter-app"
  filter-names-list: "Bread,Milk,Cheese,Eggs,Butter,Orange Juice,Cereal,Rice,Chicken,Beef"
  filter-names-store: "filter-names-store"
  topics:
    filter-names-topic: "filter-names-topic"
    source: "data-products-topic-raw"
    sink: "data-products-topic"
  user:
    username: "filter-user"
    password: "filter-user-password"
