services:

  sprint_3_app:
    image: sprint_3_app:latest
    networks:
      - sprint_3_app_net
      - sprint_3_kafka_net
    environment:
      - FAKE_LOAD_MESSAGES=500

networks:
  sprint_3_app_net:
    external: true
  sprint_3_kafka_net:
    external: true