version: "3.5"

x-kafka-common: &kafka-common
  image: bitnami/kafka:3.7
  restart: none
  networks:
    - proxynet_task_2

x-kafka-common-env: &kafka-common-env
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
  KAFKA_KRAFT_CLUSTER_ID: practicum
  KAFKA_ENABLE_KRAFT: yes
  KAFKA_CFG_PROCESS_ROLES: broker,controller
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,CONTROLLER:SSL,EXTERNAL:SSL
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: SSL

  KAFKA_CFG_SSL_ENABLED_PROTOCOL: TLSv1.2
  KAFKA_CFG_TRUSTSTORE_TYPE: JKS
  KAFKA_CFG_KEYSTORE_TYPE: JKS
  KAFKA_CFG_SSL_CLIENT_AUTH: required
  KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: password
  KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.truststore.jks
  KAFKA_CFG_SSL_KEYSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.keystore.jks
  KAFKA_CFG_SSL_KEY_PASSWORD: password
  KAFKA_CFG_SSL_KEYSTORE_PASSWORD: password

services:

  kafka-0:
    <<: *kafka-common
    container_name: kafka-0
    ports:
      - "127.0.0.1:9094:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_LISTENERS: SSL://kafka-0:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: SSL://kafka-0:9092,EXTERNAL://127.0.0.1:9094
    volumes:
      - kafka_0_data_sprint_5_task_2:/bitnami/kafka
      - ./task_2/kafka-0:/bitnami/kafka/config/certs

  kafka-1:
    <<: *kafka-common
    container_name: kafka-1
    ports:
      - "127.0.0.1:9095:9095"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: SSL://kafka-1:9092,CONTROLLER://:9093,EXTERNAL://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: SSL://kafka-1:9092,EXTERNAL://127.0.0.1:9095
    volumes:
      - kafka_1_data_sprint_5_task_2:/bitnami/kafka
      - ./task_2/kafka-1:/bitnami/kafka/config/certs

  kafka-2:
    <<: *kafka-common
    container_name: kafka-2
    ports:
      - "127.0.0.1:9096:9096"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: SSL://kafka-2:9092,CONTROLLER://:9093,EXTERNAL://:9096
      KAFKA_CFG_ADVERTISED_LISTENERS: SSL://kafka-2:9092,EXTERNAL://127.0.0.1:9096
    volumes:
      - kafka_2_data_sprint_5_task_2:/bitnami/kafka
      - ./task_2/kafka-2:/bitnami/kafka/config/certs

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    restart: always
    ports:
      - "127.0.0.1:8086:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092
      KAFKA_CLUSTERS_0_NAME: kraft
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /ui_certs
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: password
    networks:
      - proxynet_task_2
    volumes:
      - ./infra/task_2/certs/client_certs:/ui_certs

networks:
  proxynet_task_2:
    name: proxynet_task_2
    external: true

volumes:
  kafka_0_data_sprint_5_task_2:
  kafka_1_data_sprint_5_task_2:
  kafka_2_data_sprint_5_task_2: