x-common-env: &x-common-env
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_ZOOKEEPER_SASL_CLIENT: true
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_DELETE_TOPIC_ENABLE: "true"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
  KAFKA_SSL_KEYSTORE_PASSWORD: password
  KAFKA_SSL_KEY_PASSWORD: password
  KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.truststore.jks
  KAFKA_SSL_TRUSTSTORE_PASSWORD: password
  KAFKA_SSL_CLIENT_AUTH: required
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
  KAFKA_SECURITY_PROTOCOL: "SSL"

  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
  KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
  KAFKA_SUPER_USERS: "User:admin;User:kafka;User:kafka1;User:kafka2;User:kafka3"
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN

  KAFKA_LOG4J_ROOT_LOGLEVEL: "DEBUG"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./task_2/jaas:/etc/zookeeper/secrets
    networks:
      - task_2_network
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl

  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    container_name: kafka-1
    hostname: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - task_2_network
    volumes:
      - ./task_2/kafka-1:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka-1:9092,SASL_PLAINTEXT://kafka-1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT
      <<: *x-common-env

  kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    container_name: kafka-2
    hostname: kafka-2
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "9095:9095"
    networks:
      - task_2_network
    volumes:
      - ./task_2/kafka-2:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9094,SASL_PLAINTEXT://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka-2:9094,SASL_PLAINTEXT://kafka-2:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SASL_SSL,SASL_PLAINTEXT:SASL_PLAINTEXT
      <<: *x-common-env

  kafka-3:
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    container_name: kafka-3
    hostname: kafka-3
    depends_on:
      - zookeeper
    ports:
      - "9096:9096"
      - "9097:9097"
    networks:
      - task_2_network
    volumes:
      - ./task_2/kafka-3:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9096,SASL_PLAINTEXT://0.0.0.0:9097
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka-3:9096,SASL_PLAINTEXT://kafka-3:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SASL_SSL,SASL_PLAINTEXT:SASL_PLAINTEXT
      <<: *x-common-env

networks:
  task_2_network:
    driver: bridge
